version: '3'
services:
  acme-sidecar:
    image: shobuprime/traefik-acme-converter
    environment:
      - WATCH_DIR=/certs
      - PROVIDER_PATH=.cloudflare.Certificates[]
      - DOMAIN=*.example.com
      - ACME_FILE_NAME=cloudflare.json
    volumes:
      - /custom/example/certs:/certs:ro
      - /custom/example/_ssl/:/app/output
