version: '3'
services:
  acme-sidecar:
    image: shobuprime/traefik-acme-converter
    environment:
      - WATCH_DIR=/custom/dir
      - INTERVAL=10
      - PROVIDER_PATH=.customProvider.Certificates[]
      - DOMAIN=custom.example.com
      - ACME_FILE_NAME=CustomACME.json
      - OUTPUT_DIR=/custom/output
    volumes:
      - /path/to/watch:/custom/dir
      - /path/to/output:/custom/output
